// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"time"
)

type Follow struct {
	FollowingUserID int32     `json:"following_user_id"`
	FollowedUserID  int32     `json:"followed_user_id"`
	CreatedAt       time.Time `json:"created_at"`
}

type Post struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	// Content of the post
	Body      string    `json:"body"`
	UserID    int32     `json:"user_id"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	Likes     int32     `json:"likes"`
}

type User struct {
	ID         int64     `json:"id"`
	Username   string    `json:"username"`
	Role       string    `json:"role"`
	CreatedAt  time.Time `json:"created_at"`
	Reputation int32     `json:"reputation"`
}
