// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, userID int32) error
	DeleteUser(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, userID int32) (Account, error)
	GetPost(ctx context.Context, id int64) (Post, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	LikePost(ctx context.Context, id int64) error
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateEmail(ctx context.Context, arg UpdateEmailParams) (int64, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateReputation(ctx context.Context, arg UpdateReputationParams) error
}

var _ Querier = (*Queries)(nil)
